#!/bin/sh -l

cmd="docker run -d -e RABBITMQ_DEFAULT_USER=$INPUT_RABBITMQ_USER -e RABBITMQ_DEFAULT_PASS=$INPUT_RABBITMQ_PASS -p $INPUT_RABBITMQ_PORT:5672 -p $INPUT_RABBITMQ_MNG_PORT:15672 rabbitmq:$INPUT_RABBITMQ_TAG"

sh -c "$cmd"